# Name and metadata of your task
task_name: 'Trading Alerts Task'
author: 'metex'
description: 'https://www.metex.co'
repositoryUrl: 'https://github.com/elijaholmos/metex-trading-alerts-task'
imageUrl: 'imageUrl'

# network value can be DEVELOPMENT , ARWEAVE or IPFS, Recommended IPFS when deploying to testnet as the cli automatically takes care of uploading the executable with the help of web3.js key
# task_executable_network: 'DEVELOPMENT'
task_executable_network: 'IPFS'

# Path to your executable webpack if the selected network is IPFS and in case of DEVELOPMENT  name it as main
task_audit_program: 'dist/main.js'

# Total round time of your task : it must be given in slots and each slot is roughly equal to 408ms
round_time: 500

audit_window: 250
submission_window: 250

# Amounts in KOII

minimum_stake_amount: 0.1

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 10

bounty_amount_per_round: 0.1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs for the account size, that holds the task data
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more task variables, please refer the type,value,description format shown below

requirementsTags:
  # - type: TASK_VARIABLE
  #   value: 'WEB3.STORAGE'
  #   description: 'used to store the data'
  - type: TASK_VARIABLE
    value: 'TIINGO_TOKEN'
    description: 'TIINGO TOKEN'
  - type: TASK_VARIABLE
    value: 'SPHERON_KEY'
    description: 'Used to store the data. Spheron offers secure, decentralized data storage using blockchain technology for enhanced reliability and transparent data management. Do not have the key? Click the Get Key button to get one.'
    retrievalInfo: 'https://faucet-api.koii.network/api/get-spheron-storage-key;GET;SYSTEM_WALLET_PUBLIC_KEY'
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'

# OPTIONAL variables variables for creating task / REQUIRED variables for update task

# OPTIONAL Only provide the taskId if you are updating the task otherwise leave blank
task_id: '3Lw4vwVXggmUo1GeyXepjZi4ozw8NR6pEBgCfkAF7zC9'

# Provide the description for changes made in new version of task
migrationDescription: 'dev testing'
